// Central location data for the 2027 Senior Trip guide + interactive map.
// Coordinates geocoded via OpenStreetMap Nominatim. Commercial links verified via web search.
const TRIP_LOCATIONS = [

  // ---------- ATHENS ----------
  { id: "athens-backpackers", name: "Athens Backpackers", category: "hostel", island: "Athens",
    lat: 37.9687, lng: 23.7303, price: "$26/night", rating: "4.4",
    link: "https://www.hostelworld.com/hostels/p/6324/athens-backpackers/", linkLabel: "Book on Hostelworld",
    blurb: "Rooftop bar with an Acropolis view, in the heart of Plaka." },
  { id: "bedbox-hostel", name: "Bedbox Hostel", category: "hostel", island: "Athens",
    lat: 37.9764, lng: 23.7259, price: "$24/night", rating: "4.3",
    link: "https://www.hostelworld.com/hostels/p/282986/bedbox-hostel/", linkLabel: "Book on Hostelworld",
    blurb: "Simple, clean and social — steps from the Ancient Agora." },
  { id: "acropolis", name: "Acropolis & Parthenon", category: "historical", island: "Athens",
    lat: 37.9716, lng: 23.7263, price: "$21 entry",
    link: "https://etickets.tap.gr/", linkLabel: "Buy official e-ticket",
    blurb: "Go right at opening to beat the heat and the crowds." },
  { id: "ancient-agora", name: "Ancient Agora", category: "historical", island: "Athens",
    lat: 37.9747, lng: 23.7225, price: "$11 entry",
    link: "https://etickets.tap.gr/", linkLabel: "Buy official e-ticket",
    blurb: "Where Socrates actually taught." },
  { id: "plaka", name: "Plaka & Anafiotika", category: "historical", island: "Athens",
    lat: 37.9729, lng: 23.7301, price: "Free",
    link: "https://www.google.com/maps/search/?api=1&query=Anafiotika+Athens+Greece", linkLabel: "View on Google Maps",
    blurb: "Whitewashed island-style alleys beneath the Acropolis." },
  { id: "o-thanasis", name: "O Thanasis", category: "food", island: "Athens",
    lat: 37.9763, lng: 23.7264, price: "~$9/meal", rating: "4.6",
    link: "https://souvlaki-othanasis.gr/?lang=en", linkLabel: "Official website",
    blurb: "The most famous souvlaki counter in Monastiraki." },
  { id: "savas", name: "Savas", category: "food", island: "Athens",
    lat: 37.9768, lng: 23.7251, price: "~$7/meal", rating: "4.5",
    link: "https://www.savvas-restaurant.com/", linkLabel: "Official website",
    blurb: "Cheap, fast, and always solid — Monastiraki late-night staple." },
  { id: "cafe-avissinia", name: "Café Avissinia", category: "food", island: "Athens",
    lat: 37.9767, lng: 23.7237, price: "~$18/person", rating: "4.5",
    link: "https://cafeavissinia.net/", linkLabel: "Official website",
    blurb: "Sit-down meze and live music above the flea market." },
  { id: "glyfada-beach", name: "Glyfada Beach", category: "beach", island: "Athens",
    lat: 37.8734, lng: 23.7330, price: "Free entry",
    link: "https://www.google.com/maps/search/?api=1&query=Glyfada+Beach+Athens+Greece", linkLabel: "View on Google Maps",
    blurb: "The closest real beach to central Athens." },
  { id: "vouliagmeni-beach", name: "Vouliagmeni Beach", category: "beach", island: "Athens",
    lat: 37.8140, lng: 23.7821, price: "Free / ~$8 sunbed",
    link: "https://www.google.com/maps/search/?api=1&query=Vouliagmeni+Beach+Athens+Greece", linkLabel: "View on Google Maps",
    blurb: "Clear turquoise water backed by cliffs, plus a mineral lake nearby." },
  { id: "gazi", name: "Gazi District", category: "nightlife", island: "Athens",
    lat: 37.9718, lng: 23.7108, price: "Free–$10 cover",
    link: "https://www.google.com/maps/search/?api=1&query=Gazi+Athens+nightlife", linkLabel: "View on Google Maps",
    blurb: "Athens' main nightlife cluster around the old gasworks." },
  { id: "a-for-athens", name: "A for Athens (Rooftop)", category: "nightlife", island: "Athens",
    lat: 37.9767, lng: 23.7257, price: "~$13 cocktails",
    link: "https://aforathens.com/bar-restaurant/", linkLabel: "Official website",
    blurb: "Rooftop cocktails with the Acropolis lit up in front of you." },
  { id: "psyrri", name: "Psyrri Bars", category: "nightlife", island: "Athens",
    lat: 37.9784, lng: 23.7249, price: "~$8 drinks",
    link: "https://www.google.com/maps/search/?api=1&query=Psyrri+Athens+bars", linkLabel: "View on Google Maps",
    blurb: "A grittier, more local bar-hopping neighborhood." },
  { id: "piraeus-port", name: "Piraeus Port (Ferries)", category: "transport", island: "Athens",
    lat: 37.9415, lng: 23.6316, price: "",
    link: "https://www.ferryhopper.com/en", linkLabel: "Book ferries on Ferryhopper",
    blurb: "Departure point for all Cyclades-bound ferries." },
  { id: "athens-airport", name: "Athens Airport (ATH)", category: "transport", island: "Athens",
    lat: 37.9373, lng: 23.9546, price: "",
    link: "https://www.google.com/travel/flights", linkLabel: "Search flights on Google Flights",
    blurb: "Eleftherios Venizelos International Airport." },

  // ---------- SANTORINI ----------
  { id: "youth-hostel-anna", name: "Youth Hostel Anna", category: "hostel", island: "Santorini",
    lat: 36.3537, lng: 25.4672, price: "$20/night", rating: "4.1",
    link: "https://www.hostelworld.com/hostels/p/1189/youth-hostel-anna/", linkLabel: "Book on Hostelworld",
    blurb: "The cheapest beds on the island, 4 min from Perissa Beach." },
  { id: "caveland", name: "Caveland Santorini", category: "hostel", island: "Santorini",
    lat: 36.4112, lng: 25.4461, price: "$35/night", rating: "4.6",
    link: "https://www.cave-land.com/", linkLabel: "Official website",
    blurb: "A converted 19th-century winery turned boutique cave hostel." },
  { id: "akrotiri", name: "Akrotiri", category: "historical", island: "Santorini",
    lat: 36.3518, lng: 25.4035, price: "$13 entry",
    link: "https://etickets.tap.gr/", linkLabel: "Buy official e-ticket",
    blurb: "A Bronze-Age town preserved under volcanic ash." },
  { id: "ancient-thera", name: "Ancient Thera", category: "historical", island: "Santorini",
    lat: 36.3636, lng: 25.4782, price: "$7 entry",
    link: "https://etickets.tap.gr/", linkLabel: "Buy official e-ticket",
    blurb: "A clifftop ruin above Kamari with sweeping Aegean views." },
  { id: "oia-castle", name: "Oia Castle Ruins", category: "historical", island: "Santorini",
    lat: 36.4602, lng: 25.3732, price: "Free",
    link: "https://www.google.com/maps/search/?api=1&query=Oia+Castle+Santorini+Greece", linkLabel: "View on Google Maps",
    blurb: "The most famous sunset-viewing spot on the island." },
  { id: "luckys-souvlakis", name: "Lucky's Souvlakis", category: "food", island: "Santorini",
    lat: 36.4149, lng: 25.4325, price: "~$5/wrap", rating: "4.6",
    link: "https://www.google.com/maps/search/?api=1&query=Lucky%27s+Souvlakis+Fira+Santorini", linkLabel: "View on Google Maps",
    blurb: "The cheapest good meal in Fira." },
  { id: "metaxi-mas", name: "Metaxi Mas", category: "food", island: "Santorini",
    lat: 36.3880, lng: 25.4579, price: "~$20/person", rating: "4.7",
    link: "https://www.santorini-metaximas.gr/en/", linkLabel: "Official website",
    blurb: "Locally loved family taverna in Exo Gonia." },
  { id: "ammoudi-fish-tavern", name: "Ammoudi Fish Tavern", category: "food", island: "Santorini",
    lat: 36.4600, lng: 25.3706, price: "~$24/person", rating: "4.6",
    link: "https://ammoudisantorini.com/", linkLabel: "Official website",
    blurb: "Fresh catch at the water's edge below Oia." },
  { id: "red-beach", name: "Red Beach", category: "beach", island: "Santorini",
    lat: 36.3488, lng: 25.3941, price: "Free entry",
    link: "https://www.google.com/maps/search/?api=1&query=Red+Beach+Santorini+Greece", linkLabel: "View on Google Maps",
    blurb: "Dramatic red volcanic cliffs near Akrotiri." },
  { id: "kamari-beach", name: "Kamari Beach", category: "beach", island: "Santorini",
    lat: 36.3768, lng: 25.4861, price: "~$10 sunbed set",
    link: "https://www.google.com/maps/search/?api=1&query=Kamari+Beach+Santorini+Greece", linkLabel: "View on Google Maps",
    blurb: "Black volcanic sand with a lively boardwalk." },
  { id: "perissa-beach", name: "Perissa Beach", category: "beach", island: "Santorini",
    lat: 36.3523, lng: 25.4723, price: "~$8 sunbed set",
    link: "https://www.google.com/maps/search/?api=1&query=Perissa+Beach+Santorini+Greece", linkLabel: "View on Google Maps",
    blurb: "Longer, quieter black-sand stretch below Ancient Thera." },
  { id: "two-brothers-bar", name: "Two Brothers Bar", category: "nightlife", island: "Santorini",
    lat: 36.4149, lng: 25.4325, price: "~$9 drinks",
    link: "https://2brothersbarsantorini.com/menus/", linkLabel: "Official website",
    blurb: "The starting point for Fira's whole bar-crawl strip since 1983." },
  { id: "francos-bar", name: "Franco's Bar", category: "nightlife", island: "Santorini",
    lat: 36.4149, lng: 25.4325, price: "~$17 cocktails",
    link: "https://francosbar.gr/", linkLabel: "Official website",
    blurb: "Iconic caldera-view sunset cocktail bar since 1979." },
  { id: "athinios-port", name: "Athinios Port (Ferries)", category: "transport", island: "Santorini",
    lat: 36.3865, lng: 25.4305, price: "",
    link: "https://www.ferryhopper.com/en", linkLabel: "Book ferries on Ferryhopper",
    blurb: "Santorini's main ferry port, south of Fira." },
  { id: "santorini-airport", name: "Santorini Airport (JTR)", category: "transport", island: "Santorini",
    lat: 36.3997, lng: 25.4767, price: "",
    link: "https://www.google.com/travel/flights", linkLabel: "Search flights on Google Flights",
    blurb: "Near Kamari and Ancient Thera." },

  // ---------- MYKONOS ----------
  { id: "paradise-beach-resort", name: "Paradise Beach Resort (Hostel & Camping)", category: "hostel", island: "Mykonos",
    lat: 37.4101, lng: 25.3557, price: "$25/night", rating: "4.0",
    link: "https://www.paradisemykonos.com/", linkLabel: "Official website",
    blurb: "Right on the sand, next to the beach club scene." },
  { id: "mykonos-camping", name: "Mykonos Camping (Paraga Beach)", category: "hostel", island: "Mykonos",
    lat: 37.4083, lng: 25.3511, price: "$22/night", rating: "4.0",
    link: "https://www.mycamp.gr/", linkLabel: "Official website",
    blurb: "Quieter beach base with easy access to town." },
  { id: "delos", name: "Delos", category: "historical", island: "Mykonos",
    lat: 37.3997, lng: 25.2683, price: "$13 entry + $22 boat",
    link: "https://www.delostours.gr/en/", linkLabel: "Book boat & tour",
    blurb: "UNESCO-listed island, birthplace of Apollo in myth." },
  { id: "windmills-mykonos", name: "Windmills of Kato Mili", category: "historical", island: "Mykonos",
    lat: 37.4468, lng: 25.3288, price: "Free",
    link: "https://www.google.com/maps/search/?api=1&query=Windmills+of+Mykonos+Kato+Mili", linkLabel: "View on Google Maps",
    blurb: "The postcard shot of Mykonos — best at golden hour." },
  { id: "little-venice", name: "Little Venice", category: "historical", island: "Mykonos",
    lat: 37.4455, lng: 25.3262, price: "Free",
    link: "https://www.google.com/maps/search/?api=1&query=Little+Venice+Mykonos+Greece", linkLabel: "View on Google Maps",
    blurb: "Historic waterfront houses built right on the sea." },
  { id: "joannas-nikos-place", name: "Joanna's Nikos Place", category: "food", island: "Mykonos",
    lat: 37.4390, lng: 25.3266, price: "~$10/meal", rating: "4.5",
    link: "https://www.tripadvisor.com/Restaurant_Review-g662620-d1189597-Reviews-Joanna_s_Nikos_Place-Mykonos_Town_Mykonos_Cyclades_South_Aegean.html", linkLabel: "View on TripAdvisor",
    blurb: "Unpretentious, generous portions, right on the beach." },
  { id: "kikis-tavern", name: "Kiki's Tavern", category: "food", island: "Mykonos",
    lat: 37.4855, lng: 25.3577, price: "~$17/person", rating: "4.7",
    link: "https://www.google.com/maps/search/?api=1&query=Kiki%27s+Tavern+Agios+Sostis+Mykonos", linkLabel: "View on Google Maps",
    blurb: "No reservations, no cards, no sign — just show up early." },
  { id: "sea-satin-market", name: "Sea Satin Market", category: "food", island: "Mykonos",
    lat: 37.4450, lng: 25.3260, price: "~$35/person", rating: "4.5",
    link: "https://www.seasatin.gr/", linkLabel: "Official website",
    blurb: "Sunset-over-the-water seafood in Little Venice." },
  { id: "paradise-beach", name: "Paradise Beach", category: "beach", island: "Mykonos",
    lat: 37.4101, lng: 25.3557, price: "Free / ~$15 sunbed",
    link: "https://www.google.com/maps/search/?api=1&query=Paradise+Beach+Mykonos+Greece", linkLabel: "View on Google Maps",
    blurb: "The island's original party beach." },
  { id: "super-paradise-beach", name: "Super Paradise Beach", category: "beach", island: "Mykonos",
    lat: 37.4148, lng: 25.3685, price: "~$20 sunbed",
    link: "https://www.google.com/maps/search/?api=1&query=Super+Paradise+Beach+Mykonos+Greece", linkLabel: "View on Google Maps",
    blurb: "A more upscale beach club scene." },
  { id: "platis-gialos", name: "Platis Gialos", category: "beach", island: "Mykonos",
    lat: 37.4149, lng: 25.3448, price: "~$12 sunbed",
    link: "https://www.google.com/maps/search/?api=1&query=Platis+Gialos+Mykonos+Greece", linkLabel: "View on Google Maps",
    blurb: "Calmer, family-friendly beach and boat-taxi hub." },
  { id: "cavo-paradiso", name: "Cavo Paradiso", category: "nightlife", island: "Mykonos",
    lat: 37.4101, lng: 25.3557, price: "$25–$45 cover",
    link: "https://www.cavoparadiso.gr/", linkLabel: "Official website & tickets",
    blurb: "One of the world's most famous superclubs, on a clifftop." },
  { id: "scorpios", name: "Scorpios", category: "nightlife", island: "Mykonos",
    lat: 37.4084, lng: 25.3502, price: "$30+ min. spend",
    link: "https://scorpios.com/", linkLabel: "Official website & reservations",
    blurb: "Sunset beach club with live music — book ahead." },
  { id: "mykonos-port", name: "Mykonos New Port (Ferries)", category: "transport", island: "Mykonos",
    lat: 37.4648, lng: 25.3232, price: "",
    link: "https://www.ferryhopper.com/en", linkLabel: "Book ferries on Ferryhopper",
    blurb: "Where high-speed ferries to/from Athens & Santorini dock." },
  { id: "mykonos-airport", name: "Mykonos Airport (JMK)", category: "transport", island: "Mykonos",
    lat: 37.4350, lng: 25.3473, price: "",
    link: "https://www.google.com/travel/flights", linkLabel: "Search flights on Google Flights",
    blurb: "Small island airport south of Mykonos Town." },
];

const CATEGORY_META = {
  hostel:     { label: "Hostels",          emoji: "🛏️", color: "#1b6ca8" },
  food:       { label: "Food",             emoji: "🍴", color: "#e0793e" },
  historical: { label: "Historical Sites", emoji: "🏛️", color: "#8a6d3b" },
  beach:      { label: "Beaches",          emoji: "🏖️", color: "#2e9e8f" },
  nightlife:  { label: "Nightlife",        emoji: "🎉", color: "#a13d8f" },
  transport:  { label: "Flights & Ferries",emoji: "✈️", color: "#5b6b6f" },
};
